port: 8000
database:
  databaseType: mongodb
  # connpath和host等二选一
  connPath: mongodb://192.168.0.12:27017
  host: 192.168.0.12
  port: 27017
  # 其他参数 authSource 在那个库创建的
  authSource: admin
  authType: username
  description:
    username: myUserAdmin
    password: new_password
  basename: mncet
login:
  username: admin
  password: admin